version: '3.1'

services:

  db:
    image: postgres
    container_name: blablacar_modeling_db
    restart: always
    ports:
        - 5432:5432
    environment:
      POSTGRES_PASSWORD: adminisyabir
    volumes:
        - /custom/mount:/var/lib/postgresql/data